name: Build and Deploy Bicep

on:
  push:
    branches:
      - main
env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.MCTSUBID }}   # set this to your Azure Subscription Id
  AZURE_RESOURCE_GROUP: BicepTest-RG   # set this to your target resource group
  AZURE_REGION: eastus

jobs:
  build-arm:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Bicep Build-1
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: sandbox/main.bicep

      #create artifact tar
      - name: 'Tar files'
        run: tar -cvf bicep-artifacts.tar ./

      #upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bicep-artifacts
          path: bicep-artifacts.tar

  deploy-resources:
    runs-on: ubuntu-latest
    needs: build-arm

    steps:
      # download and extract artifacts
      - uses: actions/download-artifact@v2
        with:
          name: bicep-artifacts

      # extract files
      - name: 'Extract Files'
        run: tar -xvf bicep-artifacts.tar

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SUBS_JSON }}

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          region: ${{ env.AZURE_REGION }}
          template: ./sandbox/main.json
